### ISSUE TITLE
Submission popup - text is braking 

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Reines-Hotel-Site#12]
On mobile and desktop versions, the price in the popup submission window is braking. 

![image](https://user-images.githubusercontent.com/26923359/34649210-1a665af8-f3b3-11e7-8a31-c6d3350f5ea4.png)

**Comment by MeanEYE** [comment]
This is `iframe` and content we can't control.

**Comment by MeanEYE** [comment]
@VladimirWebDev test if this is something we can have an effect on. Try increasing dialog size and see fi the content responds to this.

**Comment by VladimirWebDev** [comment]
Same problem is on mobile version. However increasing size of dialog doesn't solve problem.

**Comment by talovdat** [comment]
That means we have no effect on this issue?

**Comment by VladimirWebDev** [comment]
Desktop is fixed but can't apply same solution on mobile. `div` that contains content should be styled differently however we can't apply styles to content inside `iframe` we doesn't have access to.
