### ISSUE TITLE
Map in footer does not work both mobile and desktop

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Reines-Hotel-Site#5]
Map in footer does not work in both mobile and desktop versions.

![image](https://cloud.githubusercontent.com/assets/26923359/26393131/85b4ec52-4071-11e7-9d3d-95c3006baf2a.png)

**Comment by MeanEYE** [comment]
Translation?

**Comment by iliyaM** [comment]
oops something went wrong

בתאריך 25 במאי 2017 13:34,‏ "Mladen Mijatov" <notifications@github.com> כתב:

**Comment by MeanEYE** [comment]
Same issue as on other site. 
Try testing in some 10 minutes or so.
